name: wheels_native_64bit
on: [push]
jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-11.0, windows-2022]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --user --upgrade cibuildwheel
      - run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS: auto64
          CIBW_SKIP: cp36-* pp*
          CIBW_ENVIRONMENT: DUCC0_OPTIMIZATION=portable
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest -x {project}/python/test
          CIBW_TEST_SKIP: cp37-* cp38-* cp310-*
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_I686_IMAGE: manylinux2014
          CIBW_MANYLINUX_PYPY_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          CIBW_MANYLINUX_PPC64LE_IMAGE: manylinux2014
          CIBW_MANYLINUX_S390X_IMAGE: manylinux2014
          CIBW_MANYLINUX_PYPY_AARCH64_IMAGE: manylinux2014
          CIBW_MANYLINUX_PYPY_I686_IMAGE: manylinux2014
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
